import { SCENE_DRAFT_SCHEMA_VERSION, SCENE_DRAFT_TRANSFORM_BOUNDS, getSceneObject, validateSceneDraft, type SceneDraft, type SceneObjectDraft, type SceneObjectDraftPatch, type SceneObjectId, type SceneObjectResponsiveOverride, type SceneResponsiveBreakpointId } from './scene-draft.ts';

export type SceneEditingTarget = { mode: 'base' } | { mode: 'override'; breakpointId: SceneResponsiveBreakpointId };
export const HOME_SCENE_DRAFT_BASELINE_V1: SceneDraft = { schemaVersion: SCENE_DRAFT_SCHEMA_VERSION, sceneId: 'home', objects: [
  { id: 'coffee-cup', name: 'Tazza', rendererType: 'coffeeCup', asset: { source: 'bundled', path: '/images/coffee-white2.png', darkPath: '/images/coffee-darkmode.png' }, anchorX: 'left', anchorY: 'top', zIndex: 6, offsetX: 0, offsetY: 0, scale: 1, rotation: -3.5, locked: true, visible: true, availability: 'permanent', responsiveOverrides: {} },
  { id: 'ink-bottle', name: 'Boccetta', rendererType: 'image', asset: { source: 'bundled', path: '/images/ink-bottle-and-cap.png' }, anchorX: 'left', anchorY: 'top', zIndex: 5, offsetX: 0, offsetY: 0, scale: 1, rotation: -6, locked: true, visible: true, availability: 'permanent', responsiveOverrides: {} },
  { id: 'seasonal-fig', name: 'Fico', rendererType: 'image', asset: { source: 'bundled', path: '/images/seasonal/day-atlas-fico-stagionale.webp' }, anchorX: 'right', anchorY: 'bottom', zIndex: 4, offsetX: 0, offsetY: 0, scale: 1, rotation: 0, locked: false, visible: true, availability: 'seasonal', responsiveOverrides: {}, seasonal: { activeFrom: '09-01', activeUntil: '09-30' } },
] };
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function migrateLegacyDraft(candidate: unknown): SceneDraft | null {
  if (!isRecord(candidate) || ![1, 2, 3].includes(candidate.schemaVersion as number) || candidate.sceneId !== 'home') return null;
  if (candidate.schemaVersion === 3 && Array.isArray(candidate.objects)) {
    const migrated = { schemaVersion: SCENE_DRAFT_SCHEMA_VERSION, sceneId: 'home', objects: candidate.objects.map((object) => isRecord(object) ? { ...object, availability: object.seasonal ? 'seasonal' : 'permanent', ...(isRecord(object.seasonal) ? { seasonal: { activeFrom: object.seasonal.activeFrom, activeUntil: object.seasonal.activeUntil } } : {}) } : object) };
    const result = validateSceneDraft(migrated);
    return result.ok ? result.value : null;
  }
  if (!isRecord(candidate.objects)) return null;
  const legacyObjects = candidate.objects;
  const objects = HOME_SCENE_DRAFT_BASELINE_V1.objects.map((baseline) => { const legacy = legacyObjects[baseline.id]; if (!isRecord(legacy)) return null; const offsetX = candidate.schemaVersion === 1 ? legacy.x : legacy.offsetX; const offsetY = candidate.schemaVersion === 1 ? legacy.y : legacy.offsetY; if (typeof offsetX !== 'number' || typeof offsetY !== 'number' || typeof legacy.scale !== 'number' || typeof legacy.rotation !== 'number' || typeof legacy.locked !== 'boolean' || typeof legacy.visible !== 'boolean') return null; return { ...baseline, offsetX, offsetY, scale: legacy.scale, rotation: legacy.rotation, locked: legacy.locked, visible: legacy.visible, responsiveOverrides: candidate.schemaVersion === 2 && isRecord(legacy.responsiveOverrides) ? legacy.responsiveOverrides : {} }; });
  if (objects.some((object) => object === null)) return null;
  const migrated: SceneDraft = { schemaVersion: SCENE_DRAFT_SCHEMA_VERSION, sceneId: 'home', objects: objects as SceneObjectDraft[] };
  return validateSceneDraft(migrated).ok ? migrated : null;
}
export function cloneBaselineSceneDraft(): SceneDraft { return structuredClone(HOME_SCENE_DRAFT_BASELINE_V1); }
export function resolveSceneDraft(candidate: unknown): SceneDraft { const result = validateSceneDraft(candidate); return result.ok ? result.value : migrateLegacyDraft(candidate) ?? cloneBaselineSceneDraft(); }
function clampTransformPatch(patch: SceneObjectDraftPatch | SceneObjectResponsiveOverride) { const next: SceneObjectResponsiveOverride = {}; for (const key of ['offsetX', 'offsetY', 'scale', 'rotation'] as const) { const value = patch[key]; if (typeof value === 'number' && Number.isFinite(value)) { const [min, max] = SCENE_DRAFT_TRANSFORM_BOUNDS[key]; next[key] = Math.min(max, Math.max(min, value)); } } if (typeof patch.visible === 'boolean') next.visible = patch.visible; return next; }
function replaceObject(draft: SceneDraft, object: SceneObjectDraft): SceneDraft { return { ...draft, objects: draft.objects.map((entry) => entry.id === object.id ? object : entry) }; }
export function updateSceneDraft(draft: SceneDraft, objectId: SceneObjectId, patch: SceneObjectDraftPatch, target: SceneEditingTarget = { mode: 'base' }): SceneDraft { const object = getSceneObject(draft, objectId); if (!object) return draft; if (target.mode === 'override') return replaceObject(draft, { ...object, responsiveOverrides: { ...object.responsiveOverrides, [target.breakpointId]: { ...object.responsiveOverrides[target.breakpointId], ...clampTransformPatch(patch) } } }); const availability = patch.availability ?? object.availability; return replaceObject(draft, { ...object, ...clampTransformPatch(patch), ...(typeof patch.locked === 'boolean' ? { locked: patch.locked } : {}), ...(Number.isInteger(patch.zIndex) ? { zIndex: Math.min(9, Math.max(1, patch.zIndex!)) } : {}), availability, ...(availability === 'seasonal' ? { seasonal: patch.seasonal ?? object.seasonal ?? { activeFrom: '01-01', activeUntil: '12-31' } } : { seasonal: undefined }) }); }
export function addSceneObject(draft: SceneDraft, object: SceneObjectDraft): SceneDraft { if (getSceneObject(draft, object.id) || !validateSceneDraft({ ...draft, objects: [...draft.objects, object] }).ok) return draft; return { ...draft, objects: [...draft.objects, object] }; }
export function createSceneResponsiveOverride(draft: SceneDraft, objectId: SceneObjectId, breakpointId: SceneResponsiveBreakpointId): SceneDraft { const object = getSceneObject(draft, objectId); return !object || object.responsiveOverrides[breakpointId] ? draft : replaceObject(draft, { ...object, responsiveOverrides: { ...object.responsiveOverrides, [breakpointId]: {} } }); }
export function removeSceneResponsiveOverride(draft: SceneDraft, objectId: SceneObjectId, breakpointId: SceneResponsiveBreakpointId): SceneDraft { const object = getSceneObject(draft, objectId); if (!object) return draft; const responsiveOverrides = { ...object.responsiveOverrides }; delete responsiveOverrides[breakpointId]; return replaceObject(draft, { ...object, responsiveOverrides }); }
