import { SCENE_DRAFT_SCHEMA_VERSION, SCENE_DRAFT_TRANSFORM_BOUNDS, getSceneObject, resolveSceneObjectForViewport, validateSceneDraft, type SceneAnchorX, type SceneAnchorY, type SceneDraft, type SceneObjectDraft, type SceneObjectDraftPatch, type SceneObjectId, type SceneObjectResponsiveOverride, type SceneObjectTransform, type SceneResponsiveBreakpointId, type ScenePresetOverrideId, type SceneViewport } from './scene-draft.ts';

export type SceneEditingTarget = { mode: 'base' } | { mode: 'override'; breakpointId: SceneResponsiveBreakpointId } | { mode: 'preset'; presetId: ScenePresetOverrideId };
export type SceneObjectAnchorInitialization = { viewport: SceneViewport; centerX: number; centerY: number; renderedWidth: number; renderedHeight: number; scale: number };
export const HOME_SCENE_DRAFT_BASELINE_V1: SceneDraft = { schemaVersion: SCENE_DRAFT_SCHEMA_VERSION, sceneId: 'home', objects: [
  { id: 'coffee-cup', name: 'Tazza', rendererType: 'coffeeCup', asset: { source: 'bundled', path: '/images/coffee-white2.png', darkPath: '/images/coffee-darkmode.png' }, anchorX: 'left', anchorY: 'top', zIndex: 6, offsetX: 0, offsetY: 0, scale: 1, rotation: -3.5, locked: true, visible: true, availability: 'permanent', responsiveOverrides: {}, presetOverrides: {} },
  { id: 'ink-bottle', name: 'Boccetta', rendererType: 'image', asset: { source: 'bundled', path: '/images/ink-bottle-and-cap.png' }, anchorX: 'left', anchorY: 'top', zIndex: 5, offsetX: 0, offsetY: 0, scale: 1, rotation: -6, locked: true, visible: true, availability: 'permanent', responsiveOverrides: {}, presetOverrides: {} },
  { id: 'seasonal-fig', name: 'Fico', rendererType: 'image', asset: { source: 'bundled', path: '/images/seasonal/day-atlas-fico-stagionale.webp' }, anchorX: 'right', anchorY: 'bottom', zIndex: 4, offsetX: 0, offsetY: 0, scale: 1, rotation: 0, locked: false, visible: true, availability: 'seasonal', responsiveOverrides: {}, presetOverrides: {}, seasonal: { activeFrom: '09-01', activeUntil: '09-30' } },
] };
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function migrateLegacyDraft(candidate: unknown): SceneDraft | null {
  if (!isRecord(candidate) || ![1, 2, 3, 4].includes(candidate.schemaVersion as number) || candidate.sceneId !== 'home') return null;
  if ((candidate.schemaVersion === 3 || candidate.schemaVersion === 4) && Array.isArray(candidate.objects)) {
    const migrated = { schemaVersion: SCENE_DRAFT_SCHEMA_VERSION, sceneId: 'home', objects: candidate.objects.map((object) => isRecord(object) ? { ...object, availability: object.seasonal ? 'seasonal' : 'permanent', presetOverrides: isRecord(object.presetOverrides) ? object.presetOverrides : {}, ...(isRecord(object.seasonal) ? { seasonal: { activeFrom: object.seasonal.activeFrom, activeUntil: object.seasonal.activeUntil } } : {}) } : object) };
    const result = validateSceneDraft(migrated);
    return result.ok ? result.value : null;
  }
  if (!isRecord(candidate.objects)) return null;
  const legacyObjects = candidate.objects;
  const objects = HOME_SCENE_DRAFT_BASELINE_V1.objects.map((baseline) => { const legacy = legacyObjects[baseline.id]; if (!isRecord(legacy)) return null; const offsetX = candidate.schemaVersion === 1 ? legacy.x : legacy.offsetX; const offsetY = candidate.schemaVersion === 1 ? legacy.y : legacy.offsetY; if (typeof offsetX !== 'number' || typeof offsetY !== 'number' || typeof legacy.scale !== 'number' || typeof legacy.rotation !== 'number' || typeof legacy.locked !== 'boolean' || typeof legacy.visible !== 'boolean') return null; return { ...baseline, offsetX, offsetY, scale: legacy.scale, rotation: legacy.rotation, locked: legacy.locked, visible: legacy.visible, responsiveOverrides: candidate.schemaVersion === 2 && isRecord(legacy.responsiveOverrides) ? legacy.responsiveOverrides : {} }; });
  if (objects.some((object) => object === null)) return null;
  const migrated: SceneDraft = { schemaVersion: SCENE_DRAFT_SCHEMA_VERSION, sceneId: 'home', objects: objects as SceneObjectDraft[] };
  return validateSceneDraft(migrated).ok ? migrated : null;
}
export function cloneBaselineSceneDraft(): SceneDraft { return structuredClone(HOME_SCENE_DRAFT_BASELINE_V1); }
export function resolveSceneDraftStrict(candidate: unknown): SceneDraft | null { const result = validateSceneDraft(candidate); if (result.ok) return result.value; return migrateLegacyDraft(candidate); }
export function resolveSceneDraft(candidate: unknown): SceneDraft { return resolveSceneDraftStrict(candidate) ?? cloneBaselineSceneDraft(); }
function clampTransformPatch(patch: SceneObjectDraftPatch | SceneObjectResponsiveOverride) { const next: SceneObjectResponsiveOverride = {}; for (const key of ['offsetX', 'offsetY', 'scale', 'rotation'] as const) { const value = patch[key]; if (typeof value === 'number' && Number.isFinite(value)) { const [min, max] = SCENE_DRAFT_TRANSFORM_BOUNDS[key]; next[key] = Math.min(max, Math.max(min, value)); } } if (typeof patch.visible === 'boolean') next.visible = patch.visible; return next; }
function replaceObject(draft: SceneDraft, object: SceneObjectDraft): SceneDraft { return { ...draft, objects: draft.objects.map((entry) => entry.id === object.id ? object : entry) }; }
export function getNaturalSceneObjectAnchors(center: Pick<SceneObjectAnchorInitialization, 'centerX' | 'centerY' | 'viewport'>): { anchorX: SceneAnchorX; anchorY: SceneAnchorY } { return { anchorX: center.centerX < center.viewport.width / 2 ? 'left' : 'right', anchorY: center.centerY < center.viewport.height / 2 ? 'top' : 'bottom' }; }
export function convertSceneObjectAnchorOffsets(transform: Pick<SceneObjectTransform, 'offsetX' | 'offsetY'>, current: { anchorX: SceneAnchorX; anchorY: SceneAnchorY }, next: { anchorX: SceneAnchorX; anchorY: SceneAnchorY }, geometry: Pick<SceneObjectAnchorInitialization, 'viewport' | 'renderedWidth' | 'renderedHeight' | 'scale'>) { const layoutWidth = geometry.renderedWidth / geometry.scale; const layoutHeight = geometry.renderedHeight / geometry.scale; return { offsetX: transform.offsetX + (current.anchorX === next.anchorX ? 0 : current.anchorX === 'left' ? layoutWidth - geometry.viewport.width : geometry.viewport.width - layoutWidth), offsetY: transform.offsetY + (current.anchorY === next.anchorY ? 0 : current.anchorY === 'top' ? layoutHeight - geometry.viewport.height : geometry.viewport.height - layoutHeight) }; }
export function initializeSceneObjectAnchors(draft: SceneDraft, objectId: SceneObjectId, geometry: SceneObjectAnchorInitialization, target: SceneEditingTarget, pendingObjectIds: ReadonlySet<SceneObjectId>) { const object = getSceneObject(draft, objectId); if (!object || !pendingObjectIds.has(objectId) || geometry.scale <= 0 || geometry.renderedWidth <= 0 || geometry.renderedHeight <= 0) return { draft, initialized: false }; const nextAnchors = getNaturalSceneObjectAnchors(geometry); const currentAnchors = { anchorX: object.anchorX, anchorY: object.anchorY }; const baseOffsets = convertSceneObjectAnchorOffsets(object, currentAnchors, nextAnchors, geometry); const resolved = resolveSceneObjectForViewport(object, geometry.viewport, target.mode === 'preset' ? target.presetId : undefined).object; const targetOffsets = convertSceneObjectAnchorOffsets(resolved, currentAnchors, nextAnchors, geometry); let nextObject: SceneObjectDraft = { ...object, ...nextAnchors, ...baseOffsets }; if (target.mode === 'preset') nextObject = { ...nextObject, presetOverrides: { ...nextObject.presetOverrides, [target.presetId]: { ...nextObject.presetOverrides[target.presetId], ...targetOffsets } } }; else if (target.mode === 'override') nextObject = { ...nextObject, responsiveOverrides: { ...nextObject.responsiveOverrides, [target.breakpointId]: { ...nextObject.responsiveOverrides[target.breakpointId], ...targetOffsets } } }; else nextObject = { ...nextObject, ...targetOffsets }; return { draft: replaceObject(draft, nextObject), initialized: true }; }
export function updateSceneDraft(draft: SceneDraft, objectId: SceneObjectId, patch: SceneObjectDraftPatch, target: SceneEditingTarget = { mode: 'base' }): SceneDraft { const object = getSceneObject(draft, objectId); if (!object) return draft; if (target.mode === 'override') return replaceObject(draft, { ...object, responsiveOverrides: { ...object.responsiveOverrides, [target.breakpointId]: { ...object.responsiveOverrides[target.breakpointId], ...clampTransformPatch(patch) } } }); if (target.mode === 'preset') return replaceObject(draft, { ...object, presetOverrides: { ...object.presetOverrides, [target.presetId]: { ...object.presetOverrides[target.presetId], ...clampTransformPatch(patch) } } }); const availability = patch.availability ?? object.availability; return replaceObject(draft, { ...object, ...clampTransformPatch(patch), ...(typeof patch.locked === 'boolean' ? { locked: patch.locked } : {}), ...(Number.isInteger(patch.zIndex) ? { zIndex: Math.min(9, Math.max(1, patch.zIndex!)) } : {}), availability, ...(availability === 'seasonal' ? { seasonal: patch.seasonal ?? object.seasonal ?? { activeFrom: '01-01', activeUntil: '12-31' } } : { seasonal: undefined }) }); }
export function addSceneObject(draft: SceneDraft, object: SceneObjectDraft): SceneDraft { if (getSceneObject(draft, object.id) || !validateSceneDraft({ ...draft, objects: [...draft.objects, object] }).ok) return draft; return { ...draft, objects: [...draft.objects, object] }; }
export function replaceSceneObjectAsset(draft: SceneDraft, objectId: SceneObjectId, asset: SceneObjectDraft['asset']): SceneDraft { const object = getSceneObject(draft, objectId); return object ? replaceObject(draft, { ...object, asset }) : draft; }
export function createSceneResponsiveOverride(draft: SceneDraft, objectId: SceneObjectId, breakpointId: SceneResponsiveBreakpointId): SceneDraft { const object = getSceneObject(draft, objectId); return !object || object.responsiveOverrides[breakpointId] ? draft : replaceObject(draft, { ...object, responsiveOverrides: { ...object.responsiveOverrides, [breakpointId]: {} } }); }
export function removeSceneResponsiveOverride(draft: SceneDraft, objectId: SceneObjectId, breakpointId: SceneResponsiveBreakpointId): SceneDraft { const object = getSceneObject(draft, objectId); if (!object) return draft; const responsiveOverrides = { ...object.responsiveOverrides }; delete responsiveOverrides[breakpointId]; return replaceObject(draft, { ...object, responsiveOverrides }); }
export function createScenePresetOverride(draft: SceneDraft, objectId: SceneObjectId, presetId: ScenePresetOverrideId): SceneDraft { const object = getSceneObject(draft, objectId); return !object || object.presetOverrides[presetId] ? draft : replaceObject(draft, { ...object, presetOverrides: { ...object.presetOverrides, [presetId]: {} } }); }
export function removeScenePresetOverride(draft: SceneDraft, objectId: SceneObjectId, presetId: ScenePresetOverrideId): SceneDraft { const object = getSceneObject(draft, objectId); if (!object) return draft; const presetOverrides = { ...object.presetOverrides }; delete presetOverrides[presetId]; return replaceObject(draft, { ...object, presetOverrides }); }
